export const LegalFields = [
  ["Tax Law", "https://www.flaticon.com/svg/static/icons/svg/1395/1395852.svg"],
  [
    "Corporate and Business Law",
    "https://www.flaticon.com/svg/static/icons/svg/2343/2343528.svg",
  ],
  [
    "Banking and Financial Law",
    "https://www.flaticon.com/svg/static/icons/svg/871/871583.svg",
  ],
  [
    "Labour Law",
    "https://www.flaticon.com/svg/static/icons/svg/1395/1395816.svg",
  ],
  [
    "Insurance Law",
    "https://www.flaticon.com/svg/static/icons/svg/1456/1456798.svg",
  ],
  [
    "International and European Law",
    "https://www.flaticon.com/svg/static/icons/svg/1396/1396381.svg",
  ],
  [
    "Criminal Law",
    "https://www.flaticon.com/svg/static/icons/svg/1309/1309846.svg",
  ],
  [
    "Intellectual Property",
    "https://www.flaticon.com/svg/static/icons/svg/1448/1448374.svg",
  ],
  [
    "Administrative Law",
    "https://www.flaticon.com/svg/static/icons/svg/953/953357.svg",
  ],
  [
    "Bankruptcy and Insolvency Law",
    "https://www.flaticon.com/svg/static/icons/svg/1611/1611953.svg",
  ],
  [
    "Consumer Law",
    "https://www.flaticon.com/svg/static/icons/svg/872/872243.svg",
  ],
  [
    "Family Law",
    "https://www.flaticon.com/svg/static/icons/svg/1318/1318189.svg",
  ],
  [
    "Migration Law",
    "https://www.flaticon.com/svg/static/icons/svg/1212/1212639.svg",
  ],
  [
    "Medical and Health Law",
    "https://www.flaticon.com/svg/static/icons/svg/872/872079.svg",
  ],
  [
    "Procedural Law",
    "https://www.flaticon.com/svg/static/icons/svg/1610/1610933.svg",
  ],
  [
    "Sports Law",
    "https://www.flaticon.com/svg/static/icons/svg/1126/1126064.svg",
  ],
  [
    "Inheritance Law",
    "https://www.flaticon.com/svg/static/icons/svg/1735/1735693.svg",
  ],
  [
    "Constitutional Law",
    "https://www.flaticon.com/svg/static/icons/svg/1309/1309845.svg",
  ],
  [
    "Building Law",
    "https://www.flaticon.com/svg/static/icons/svg/871/871925.svg",
  ],
  [
    "Competition Law",
    "https://www.flaticon.com/svg/static/icons/svg/832/832609.svg",
  ],
  [
    "Contract Law",
    "https://www.flaticon.com/svg/static/icons/svg/871/871968.svg",
  ],
  // [
  //   "Property Law",
  //   "https://www.flaticon.com/svg/static/icons/svg/1456/1456792.svg",
  // ],
  [
    "Tenancy Law",
    "https://www.flaticon.com/svg/static/icons/svg/1454/1454074.svg",
  ],
  [
    "Personal Rights Law",
    "https://www.flaticon.com/svg/static/icons/svg/875/875677.svg",
  ],
  ["Tort Law", "https://www.flaticon.com/svg/static/icons/svg/871/871857.svg"],
  [
    "Real Rights Law(Ownership, possession, land registry, etc.)",
    "https://www.flaticon.com/svg/static/icons/svg/1456/1456792.svg",
  ],
  ["Other", "https://www.flaticon.com/svg/static/icons/svg/956/956696.svg"],
];

export const services = [
  "Contract drafting",
  "Claim & objection",
  "Legal advices",
  "Other services",
];

export const languages = [
  "‪Afrikaans‬",
  "‪azərbaycan‬",
  "‪català‬",
  "‪Čeština‬",
  "‪Dansk‬",
  "‪Deutsch‬",
  "‪eesti‬",
  "‪English (United Kingdom)‬",
  "‪English (United States)‬",
  "‪Español (España)‬",
  "‪Español (Latinoamérica)‬",
  "‪euskara‬",
  "‪Filipino‬",
  "‪Français (Canada)‬",
  "‪Français (France)‬",
  "‪galego‬",
  "‪Hrvatski‬",
  "‪Indonesia‬",
  "‪isiZulu‬",
  "‪íslenska‬",
  "‪Italiano‬",
  "‪Kiswahili‬",
  "‪latviešu‬",
  "‪lietuvių‬",
  "‪magyar‬",
  "‪Melayu‬",
  "‪Nederlands‬",
  "‪norsk‬",
  "‪polski‬",
  "‪Português (Brasil)‬",
  "‪Português (Portugal)‬",
  "‪română‬",
  "‪Slovenčina‬",
  "‪slovenščina‬",
  "‪Suomi‬",
  "‪Svenska‬",
  ">",
  "‪Türkçe‬",
  "‪Ελληνικά‬",
  "‪български‬",
  "‪монгол‬",
  "‪Русский‬",
  "‪Українська‬",
  "‪ქართული‬",
  "‪հայերեն‬",
  "‫עברית‬‎",
  "‫اردو‬‎",
  "‫العربية‬‎",
  "‫فارسی‬‎",
  "‪አማርኛ‬",
  "‪नेपाली‬",
  "‪मराठी‬",
  "‪हिन्दी‬",
  "‪বাংলা‬",
  "‪ગુજરાતી‬",
  "‪தமிழ்‬",
  "‪తెలుగు‬",
  "‪ಕನ್ನಡ‬",
  "‪മലയാളം‬",
  "‪සිංහල‬",
  "‪ไทย‬",
  "‪ລາວ‬",
  "‪မြန်မာ‬",
  "‪ខ្មែរ‬",
  "‪한국어‬",
  "‪中文（香港）‬",
  "‪日本語‬",
  "‪简体中文‬",
  "‪繁體中文‬",
];

export const locations = [
  "Zürich (ZH)",
  "Bern / Berne (BE)",
  "Luzern (LU)",
  "Uri (UR)",
  "Schwyz (SZ)",
  "Obwalden (OW)",
  "Nidwalden (NW)",
  "Glarus (GL)",
  "Zug (ZG)",
  "Freiburg / Fribourg (FR)",
  "Solothurn (SO)",
  "Basel Stadt (BS)",
  "Basel Land (BL)",
  "Schaffhausen (SH)",
  "Appenzell Ausserrhoden (AR)",
  "Appenzell Innerrhoden (AI)",
  "Sankt Gallen (SG)",
  "Graubünden (GR)",
  "Aargau (AG)",
  "Thurgau (TG)",
  "Ticino (TI)",
  "Vaud (VD)",
  "Valais / Wallis (VS)",
  "Neuchâtel (NE)",
  "Genève (GE)",
  "Jura (JU)",
];

export const EnglishError = [
  "First Name should be at least 3 characters long",
  "Last Name should be at least 3 characters long",
  "Invalid Email address",
  "Passwords do not match",
];